# Generated by Django 4.2.26 on 2026-01-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moviedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('year', models.IntegerField()),
                ('typ', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('duration', models.FloatField()),
            ],
        ),
    ]
