# Generated by Django 4.2.26 on 2026-01-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='type',
            field=models.CharField(default='Action', max_length=200),
        ),
    ]
