# Generated by Django 4.2.26 on 2026-01-30 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedata_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviedata',
            old_name='type',
            new_name='typ',
        ),
    ]
