# Generated by Django 4.2.26 on 2026-01-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_moviedata_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='images/default.avif', upload_to='images'),
        ),
    ]
