# Generated by Django 5.2.8 on 2025-11-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_items_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://cdn-icons-png.freepik.com/512/7997/7997145.png', max_length=500),
        ),
    ]
