# Generated by Django 4.2.26 on 2025-12-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_item_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://cdn-icons-png.freepik.com/512/7997/7997145.png', max_length=500),
        ),
    ]
