# Generated by Django 5.2.8 on 2025-12-04 13:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_category_added_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='added_on',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.URLField(default='https://cdn-icons-png.freepik.com/512/7997/7997145.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.URLField(default='https://cdn-icons-png.freepik.com/512/7997/7997145.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
