# Generated by Django 5.2.8 on 2025-12-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_added_on_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
    ]
