# Generated by Django 5.2.8 on 2025-12-05 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_item_item_name_alter_item_item_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['user_name', 'item_price'], name='myapp_item_user_na_18bfbe_idx'),
        ),
    ]
